version: '3'

networks:
  services:
    ipam:
      config:
        - subnet: 173.17.0.0/24

services:
  #
  # Webserver
  #
  webserver:
    image: indy-node
    build:
      context: .
      dockerfile: pool.dockerfile
    command: 'bash -c ''./scripts/start_webserver.sh'''
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - HOST=173.17.0.100
      - RUST_LOG=${RUST_LOG}
    networks:
      services:
        ipv4_address: 173.17.0.100
    ports:
      - 9000:8000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    volumes:
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - node1-data:/home/indy/.mnt/node1
      - node2-data:/home/indy/.mnt/node2
      - node3-data:/home/indy/.mnt/node3
      - node4-data:/home/indy/.mnt/node4

  #
  # Nodes
  #
  node1:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 1'''
    networks:
      services:
        ipv4_address: 173.17.0.101
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data:/home/indy/ledger

  node2:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 2'''
    networks:
      services:
        ipv4_address: 173.17.0.102
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node2-data:/home/indy/ledger

  node3:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 3'''
    networks:
      services:
        ipv4_address: 173.17.0.103
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data:/home/indy/ledger

  node4:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 4'''
    networks:
      services:
        ipv4_address: 173.17.0.104
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data:/home/indy/ledger

  #
  # Agents
  #
  asset:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2019/12/christmas-squares-pattern-seamless.png
      - THEME=DarkGray
      - PORT=3005
      - NAME=Asset
      - EMAIL=asset@DROM
      - TAX_ID=999-50-3005
      - PASSWORD=2020
      - USERNAME=asset
      - PUBLIC_DID_ENDPOINT=173.17.0.150:3005
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3005:3005
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.150
    volumes:
      - node1-data:/home/indy/ledger

  roland:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2019/02/fresh-spring-colors-pattern.png
      - THEME=BurlyWood
      - PORT=3001
      - NAME=Roland
      - EMAIL=roland@DROM
      - TAX_ID=999-50-3001
      - PASSWORD=2020
      - USERNAME=roland
      - PUBLIC_DID_ENDPOINT=173.17.0.160:3001
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3001:3001
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - asset
    networks:
      services:
        ipv4_address: 173.17.0.160
    volumes:
      - node1-data:/home/indy/ledger

  marta:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2019/10/squares-pattern.png
      - THEME=OliveDrab
      - PORT=3002
      - NAME=Marta
      - EMAIL=marta@DROM
      - TAX_ID=999-50-3002
      - PASSWORD=2020
      - USERNAME=marta
      - PUBLIC_DID_ENDPOINT=173.17.0.170:3002
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3002:3002
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - asset
    networks:
      services:
        ipv4_address: 173.17.0.170
    volumes:
      - node1-data:/home/indy/ledger

  luisa:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2020/02/dotted-fruits-pattern.png
      - THEME=LightSteelBlue
      - PORT=3003
      - NAME=Luisa
      - EMAIL=luisa@DROM
      - TAX_ID=999-50-3003
      - PASSWORD=2020
      - USERNAME=luisa
      - PUBLIC_DID_ENDPOINT=173.17.0.180:3003
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3003:3003
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - asset
    networks:
      services:
        ipv4_address: 173.17.0.180
    volumes:
      - node1-data:/home/indy/ledger

  andrei:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2020/06/honeycomb-pattern.png
      - THEME=Coral
      - PORT=3004
      - NAME=Andrei
      - EMAIL=andrei@DROM
      - TAX_ID=999-50-3004
      - PASSWORD=2020
      - USERNAME=andrei
      - PUBLIC_DID_ENDPOINT=173.17.0.190:3004
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3004:3004
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - asset
    networks:
      services:
        ipv4_address: 173.17.0.190
    volumes:
      - node1-data:/home/indy/ledger

  cemil:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2020/07/yellow-pink-sunny-halftone-pattern-768x512.jpg
      - THEME=OliveDrab
      - PORT=3006
      - NAME=Cemil
      - EMAIL=cemil@DROM
      - TAX_ID=999-50-3006
      - PASSWORD=2020
      - USERNAME=cemil
      - PUBLIC_DID_ENDPOINT=173.17.0.191:3006
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3006:3006
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - asset
    networks:
      services:
        ipv4_address: 173.17.0.191
    volumes:
      - node1-data:/home/indy/ledger

  koraltan:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://www.psdgraphics.com/wp-content/uploads/2020/07/retro-brown-hexagons-pattern-768x512.jpg
      - THEME=OliveDrab
      - PORT=3007
      - NAME=Koraltan
      - EMAIL=koraltan@DROM
      - TAX_ID=999-50-3007
      - PASSWORD=2020
      - USERNAME=koraltan
      - PUBLIC_DID_ENDPOINT=173.17.0.181:3007
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3007:3007
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - asset
    networks:
      services:
        ipv4_address: 173.17.0.181
    volumes:
      - node1-data:/home/indy/ledger

volumes:
  webserver-cli:
  node1-data:
  node2-data:
  node3-data:
  node4-data: